#! /usr/bin/env python

Import( 'env' )

env = env.Copy()

env.MergeFlags( env['LASH10_FLAGS'] )
env.MergeFlags( env['QTGUI_FLAGS'] )
env.MergeFlags( '-I#/libqlash -L#/libqlash -lqlash' )
env.Program( target="simple_lash_client", source=["main.cpp"] )

