#! /usr/bin/env python
## This script is a quick test to demonstrate (and test) 
## the bksys moc handling '#include "file.moc"' can be added .. or not
##
## Thomas Nagy, 2005
## This file can be reused freely for any project (see COPYING)

Import( 'env' )

obj=env.qt4obj('staticlib', env)
obj.target='libjackmix_backend'
obj.source='\
	jack_backend.cpp \
'
obj.libs="QtCore"
obj.includes='#/ ./'
obj.execute()

#testapp=env.qt4obj('program', env)
#testapp.target="configtest"
#testapp.source="configtest.cpp"
#testapp.libs="libcore QtCore"
#testapp.libpaths="#/ ./"
#testapp.execute()
#
#testapp2=env.qt4obj('program', env)
#testapp2.target="namedtreemodel_test"
#testapp2.source="namedtreemodel_test.cpp"
#testapp2.libs="libcore QtCore QtGui QtXml"
#testapp2.libpaths="#/ ./"
#testapp2.execute()
#
#testapp3=env.qt4obj('program', env)
#testapp3.target="abstractnamedtreeitem_test"
#testapp3.source="abstractnamedtreeitem_test.cpp"
#testapp3.libs="libcore QtCore QtXml"
#testapp3.libpaths="#/ ./"
#testapp3.execute()
#
#testapp4=env.qt4obj('program', env)
#testapp4.target="datasetchain_test"
#testapp4.source="datasetchain_test.cpp"
#testapp4.libs="libcore QtCore"
#testapp4.libpaths="#/ ./"
#testapp4.execute()
