#! /usr/bin/env python

Import( 'env' )

env = env.Clone()

env.AppendUnique( CPPPATH = ["#/libmatrix","#/libgui","#/libcore"] )
env.StaticLibrary( target="jackmix_mixingelements", source=["stereo_elements.cpp","aux_elements.cpp"] )

