#! /usr/bin/env python

Import( 'env' )

env = env.Clone()

env.MergeFlags( "-I#/libcore -I#/libgui -I#/libelements -I#/libcontrol -I#/libmatrix -I#/backend" )
env.StaticLibrary( target="jackmix_mixingmatrix", source=["mixingmatrix.cpp"] )

