#! /usr/bin/env python
## This script is a quick test to demonstrate (and test) 
## the bksys moc handling '#include "file.moc"' can be added .. or not
##
## Thomas Nagy, 2005
## This file can be reused freely for any project (see COPYING)

Import( 'env' )

obj=env.qt4obj('staticlib', env)
obj.target='libjackmix_gui'
obj.source='\
	channelselector.cpp \
	slider.cpp \
	qfloatcontrol.cpp \
	qfloatslider.cpp \
	qfloatpoti.cpp \
	qtickmarks.cpp \
	volumeslider.cpp \
	stereovolumeslider.cpp \
	qsynthKnob.cpp \
'
#	qpoti.cpp \
#	qpixmapeffect.cpp \
#	qimageeffect.cpp \
obj.libs="QtCore"
obj.includes='#/ ./'
obj.execute()

testapp=env.qt4obj('program', env)
testapp.target="qfloatcontrol_test"
testapp.source="qfloatcontrol_test.cpp"
testapp.libs="jackmix_gui QtGui QtCore"
testapp.libpaths="#/ ./"
testapp.execute()

testapp2=env.qt4obj('program', env)
testapp2.target="poti_test"
testapp2.source="poti_test.cpp"
testapp2.libs="jackmix_gui QtCore QtGui"
testapp2.libpaths="#/ ./"
testapp2.execute()

estapp3=env.qt4obj('program', env)
estapp3.target="slider_test"
estapp3.source="slider_test.cpp"
estapp3.libs="jackmix_gui QtGui QtCore"
estapp3.libpaths="#/ ./"
estapp3.execute()

testapp4=env.qt4obj('program', env)
testapp4.target="channelselector_test"
testapp4.source="channelselector_test.cpp"
testapp4.libs="jackmix_gui QtGui QtCore"
testapp4.libpaths="#/ ./"
testapp4.execute()
