#! /usr/bin/env python
## This script is a quick test to demonstrate (and test) 
## the bksys moc handling '#include "file.moc"' can be added .. or not
##
## Thomas Nagy, 2005
## This file can be reused freely for any project (see COPYING)

Import( 'env' )

obj=env.qt4obj('staticlib', env)
obj.target='libjackmix_gui'
obj.source='\
	channelselector.cpp \
	graphicalguiserver.cpp \
	abstractslider.cpp \
	slider.cpp \
	knob.cpp \
'
obj.libs="QtCore"
obj.includes='#/ ./ ../libcore'
obj.execute()

testapp3=env.qt4obj('program', env)
testapp3.target="slider_test"
testapp3.source="slider_test.cpp"
testapp3.includes='#/ ./ ../libcore'
testapp3.libs="jackmix_gui QtGui QtCore"
testapp3.libpaths="#/ ./"
testapp3.execute()

testapp4=env.qt4obj('program', env)
testapp4.target="channelselector_test"
testapp4.source="channelselector_test.cpp"
testapp4.libs="jackmix_gui QtGui QtCore"
testapp4.libpaths="#/ ./"
testapp4.execute()
